name: writings

on:
  push:
    paths:
      - 'input.txt'

env:
  DEVOPS_DIR: devops

jobs:
  writing:
    name: 1
    runs-on: ubuntu-latest
    steps:
    - name: 1
      uses: actions/checkout@v3
      with:
        repository: mrzgardini/mrzgardini.github.io
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: 2
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://github.com/mrzgardini/mrzgardini.github.io.git
        git clone https://github.com/mrzgardini/writings.git
        python writings/writings.py
        cd mrzgardini.github.io
        git config --local user.email "mrzgardini@gmail.com"
        git config --local user.name "mrzgardini"
        git add *
        git commit -a -m "mrzgardini"
        git remote set-url --push origin https://mrzgardini:${{ secrets.GITHUB_TOKEN }}@github.com/mrzgardini/mrzgardini.github.io
        git push
