name: writings

on:
  push:
    paths:
      - 'input.txt'

permissions:
  contents: write

jobs:
  writings:
    name: 1
    runs-on: ubuntu-latest
    steps:
    - name: 1
      uses: actions/checkout@v3
      with:
        repository: mrzgardini/mrzgardini.github.io.git
        run: |
          git clone https://github.com/mrzgardini/mrzgardini.github.io.git
          git clone https://github.com/mrzgardini/writings.git
          python writings/writings.py
          cd mrzgardini.github.io
          git config --local user.email "mrzgardini@gmail.com"
          git config --local user.name "mrzgardini"
          git add *
          git commit -a -m "mrzgardini"
          git remote set-url --push origin https://mrzgardini:${{ secrets.GITHUB_TOKEN }}@github.com/mrzgardini/mrzgardini.github.io
          git push
